# Use official Node.js LTS image
FROM node:24

# Set working directory
WORKDIR /src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy app source code
COPY . .

# Expose port your app runs on (use 3000 or appropriate port)
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
